/**
 * Authored audits and activity drafts.
 *
 * The PRNG chooses dates, not prose. Every title, description, and tag is a
 * constant so the corpus cannot drift between machines and so future search
 * has the exact terms SEARCH_SPEC.md §6 needs on the hero.
 */
import {
  cyberScenario,
  financialScenario,
  legalScenario,
  procurementScenario,
} from "@/lib/audit/scenarios";
import type { Actor, Scenario } from "@/lib/audit/types";
import { HERO_AUDIT_ID, HERO_EXECUTION_ID, HERO_OPENED_AT } from "./rng";
import type { ActivityStatus, ActivityType, SimulatedAudit } from "./types";

export const ACTIVITY_TYPES: readonly ActivityType[] = [
  "audit",
  "control_test",
  "evidence_review",
  "finding",
  "follow_up",
  "human_review",
  "compliance_check",
  "vendor_review",
  "access_review",
];

/** The phrase and tags that later search must be able to recover the hero by. */
export const HERO_SEARCH_TAGS = [
  "revenue",
  "recognition",
  "revenue recognition",
  "revenue recognition exception",
  "rev-rec",
  "REV-REC-01",
  "exception",
  "exceptions",
  "flagged",
  "september",
  "2026-09",
  "Q3",
  "approval",
  "approval missing",
  "contract",
  "C-1001",
  "C-1002",
  "invoice",
  "deferred revenue",
  "performance obligation",
  "1.42M",
  "1420000",
  "financial audit",
] as const;

export interface ActivityDraft {
  readonly type: ActivityType;
  readonly scenario: Scenario;
  readonly title: string;
  readonly description: string;
  readonly auditId: string;
  readonly executionId: string | null;
  readonly status: ActivityStatus;
  readonly findingId: string | null;
  readonly actor: Actor;
  readonly searchTags: readonly string[];
  readonly coolBacked: boolean;
  /** When set, this row is pinned to a logical time and not re-dated. */
  readonly pinnedAt?: string;
}

export const AUDITS: readonly SimulatedAudit[] = [
  {
    auditId: HERO_AUDIT_ID,
    scenario: "financial",
    title: financialScenario.title,
    period: financialScenario.period,
    openedAt: financialScenario.openedAt,
    closedAt: "2026-09-15T12:33:00.000Z",
    status: "completed",
    isHero: true,
    executionIds: [HERO_EXECUTION_ID],
    artifactIds: financialScenario.artifacts.map((a) => a.artifactId),
    summary: {
      controlsTested: 12,
      controlsPassed: 9,
      exceptions: 3,
      findings: 3,
      humanReviewCompleted: true,
    },
    searchTags: [...HERO_SEARCH_TAGS, ...financialScenario.searchTags],
    hasEngineTrail: true,
  },
  {
    auditId: "AUD-FIN-2026-08",
    scenario: "financial",
    title: "August Accrual Completeness Review",
    period: "2026-Q3",
    openedAt: "2026-08-28T09:30:00.000Z",
    closedAt: "2026-09-04T16:10:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-FIN-2026-08-001"],
    artifactIds: [],
    summary: {
      controlsTested: 6,
      controlsPassed: 5,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["accrual", "completeness", "august", "journal entry"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-FIN-2026-10",
    scenario: "financial",
    title: "October Revenue Cut-off Testing",
    period: "2026-Q4",
    openedAt: "2026-10-20T08:45:00.000Z",
    closedAt: "2026-10-22T17:05:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-FIN-2026-10-001"],
    artifactIds: [],
    summary: {
      controlsTested: 8,
      controlsPassed: 6,
      exceptions: 2,
      findings: 2,
      humanReviewCompleted: true,
    },
    searchTags: ["revenue", "cut-off", "october", "Q4"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-FIN-2026-11",
    scenario: "financial",
    title: "Q4 Deferred Revenue Audit",
    period: "2026-Q4",
    openedAt: "2026-11-10T09:15:00.000Z",
    closedAt: "2026-11-12T15:40:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-FIN-2026-11-001"],
    artifactIds: [],
    summary: {
      controlsTested: 7,
      controlsPassed: 6,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["revenue", "deferred revenue", "Q4", "rollforward"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-FIN-2026-12",
    scenario: "financial",
    title: "Revenue Contract Modification Review",
    period: "2026-Q4",
    openedAt: "2026-12-02T10:00:00.000Z",
    closedAt: "2026-12-04T14:20:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-FIN-2026-12-001"],
    artifactIds: [],
    summary: {
      controlsTested: 5,
      controlsPassed: 4,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["revenue", "contract", "modification", "Q4"],
    hasEngineTrail: false,
  },
  {
    auditId: legalScenario.auditId,
    scenario: "legal",
    title: legalScenario.title,
    period: legalScenario.period,
    openedAt: legalScenario.openedAt,
    closedAt: "2026-09-18T16:45:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: [legalScenario.executionId],
    artifactIds: legalScenario.artifacts.map((a) => a.artifactId),
    summary: {
      controlsTested: 8,
      controlsPassed: 6,
      exceptions: 2,
      findings: 2,
      humanReviewCompleted: true,
    },
    searchTags: [
      ...legalScenario.searchTags,
      "gdpr processor obligations",
      "processor agreement",
    ],
    hasEngineTrail: true,
  },
  {
    auditId: "AUD-LEG-2026-10",
    scenario: "legal",
    title: "Contract Approval Compliance Review",
    period: "2026-Q4",
    openedAt: "2026-10-08T09:00:00.000Z",
    closedAt: "2026-10-10T13:30:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-LEG-2026-10-001"],
    artifactIds: [],
    summary: {
      controlsTested: 6,
      controlsPassed: 5,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["approval", "contract", "compliance", "sign-off"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-LEG-2026-11",
    scenario: "legal",
    title: "Data Processing Agreement Refresh",
    period: "2026-Q4",
    openedAt: "2026-11-18T10:30:00.000Z",
    closedAt: "2026-11-20T15:00:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-LEG-2026-11-001"],
    artifactIds: [],
    summary: {
      controlsTested: 5,
      controlsPassed: 5,
      exceptions: 0,
      findings: 0,
      humanReviewCompleted: true,
    },
    searchTags: ["dpa", "processor", "gdpr", "agreement"],
    hasEngineTrail: false,
  },
  {
    auditId: cyberScenario.auditId,
    scenario: "cyber",
    title: cyberScenario.title,
    period: cyberScenario.period,
    openedAt: cyberScenario.openedAt,
    closedAt: "2026-09-26T17:10:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: [cyberScenario.executionId],
    artifactIds: cyberScenario.artifacts.map((a) => a.artifactId),
    summary: {
      controlsTested: 10,
      controlsPassed: 7,
      exceptions: 3,
      findings: 3,
      humanReviewCompleted: false,
    },
    searchTags: [...cyberScenario.searchTags, "mfa exception", "inactive account"],
    hasEngineTrail: true,
  },
  {
    auditId: "AUD-CYB-2026-10",
    scenario: "cyber",
    title: "Quarterly Administrator Access Recertification",
    period: "2026-Q4",
    openedAt: "2026-10-28T08:20:00.000Z",
    closedAt: "2026-10-30T16:00:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-CYB-2026-10-001"],
    artifactIds: [],
    summary: {
      controlsTested: 4,
      controlsPassed: 3,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["administrator access", "recertification", "access review"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-CYB-2026-11",
    scenario: "cyber",
    title: "Incident Response Tabletop Follow-up",
    period: "2026-Q4",
    openedAt: "2026-11-24T13:00:00.000Z",
    closedAt: null,
    status: "in_review",
    isHero: false,
    executionIds: ["EXEC-CYB-2026-11-001"],
    artifactIds: [],
    summary: {
      controlsTested: 3,
      controlsPassed: 3,
      exceptions: 0,
      findings: 0,
      humanReviewCompleted: false,
    },
    searchTags: ["incident response", "tabletop", "cyber"],
    hasEngineTrail: false,
  },
  {
    auditId: procurementScenario.auditId,
    scenario: "procurement",
    title: procurementScenario.title,
    period: procurementScenario.period,
    openedAt: procurementScenario.openedAt,
    closedAt: "2026-10-02T12:20:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: [procurementScenario.executionId],
    artifactIds: procurementScenario.artifacts.map((a) => a.artifactId),
    summary: {
      controlsTested: 9,
      controlsPassed: 7,
      exceptions: 2,
      findings: 2,
      humanReviewCompleted: true,
    },
    searchTags: [
      ...procurementScenario.searchTags,
      "vendor invoice variance",
      "goods receipt",
    ],
    hasEngineTrail: true,
  },
  {
    auditId: "AUD-PRC-2026-10",
    scenario: "procurement",
    title: "Northgate Logistics Vendor Risk Review",
    period: "2026-Q4",
    openedAt: "2026-10-14T09:40:00.000Z",
    closedAt: "2026-10-16T11:55:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-PRC-2026-10-001"],
    artifactIds: [],
    summary: {
      controlsTested: 5,
      controlsPassed: 4,
      exceptions: 1,
      findings: 1,
      humanReviewCompleted: true,
    },
    searchTags: ["vendor", "northgate", "risk review"],
    hasEngineTrail: false,
  },
  {
    auditId: "AUD-PRC-2026-11",
    scenario: "procurement",
    title: "Year-end Purchase Accrual Review",
    period: "2026-Q4",
    openedAt: "2026-11-27T08:50:00.000Z",
    closedAt: "2026-12-01T16:30:00.000Z",
    status: "completed",
    isHero: false,
    executionIds: ["EXEC-PRC-2026-11-001"],
    artifactIds: [],
    summary: {
      controlsTested: 6,
      controlsPassed: 6,
      exceptions: 0,
      findings: 0,
      humanReviewCompleted: true,
    },
    searchTags: ["purchase", "accrual", "year-end", "vendor"],
    hasEngineTrail: false,
  },
];

/**
 * 55 authored rows. Counts match SIMULATION_SPEC.md §4.
 * The three pinned hero rows occupy the oldest window.
 */
export const ACTIVITY_DRAFTS: readonly ActivityDraft[] = [
  // ── audit × 8 ────────────────────────────────────────────────────────────
  {
    type: "audit",
    scenario: "financial",
    title: "September Revenue Recognition Audit",
    description:
      "AI tested 12 revenue-recognition controls against the Q3 ledger, contracts C-1001 and C-1002, and policy REV-POL-3. Three exceptions were raised; human review completed.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "exception",
    findingId: "F-FIN-001",
    actor: "system",
    searchTags: HERO_SEARCH_TAGS,
    coolBacked: true,
    pinnedAt: HERO_OPENED_AT,
  },
  {
    type: "audit",
    scenario: "financial",
    title: "October Revenue Cut-off Testing",
    description:
      "Cut-off sample over late-October invoices and shipping evidence. Two timing exceptions recorded against the Q4 close calendar.",
    auditId: "AUD-FIN-2026-10",
    executionId: "EXEC-FIN-2026-10-001",
    status: "exception",
    findingId: "F-FIN-010",
    actor: "system",
    searchTags: ["revenue", "cut-off", "october", "invoice"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "financial",
    title: "Q4 Deferred Revenue Audit",
    description:
      "Rollforward of deferred revenue balances into Q4. One schedule line could not be tied to an open performance obligation.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "exception",
    findingId: "F-FIN-011",
    actor: "system",
    searchTags: ["revenue", "deferred revenue", "Q4"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "financial",
    title: "Revenue Contract Modification Review",
    description:
      "Reviewed mid-quarter modifications on three material contracts. One change order lacked a signed amendment.",
    auditId: "AUD-FIN-2026-12",
    executionId: "EXEC-FIN-2026-12-001",
    status: "exception",
    findingId: "F-FIN-012",
    actor: "system",
    searchTags: ["revenue", "contract", "modification"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "legal",
    title: "GDPR Processor Obligations Review closed",
    description:
      "Engagement closed: 8 controls, 2 exceptions (unmapped Art.32 clause, retention shortfall). Trail available on AUD-LEG-2026-08.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "exception",
    findingId: "F-LEG-001",
    actor: "system",
    searchTags: ["gdpr", "processor obligations", "REG-MAP-01"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "legal",
    title: "Contract Approval Compliance Review",
    description:
      "Sampled 22 newly executed agreements for approval-matrix compliance. One vendor MSA was countersigned below the required grade.",
    auditId: "AUD-LEG-2026-10",
    executionId: "EXEC-LEG-2026-10-001",
    status: "exception",
    findingId: "F-LEG-010",
    actor: "system",
    searchTags: ["approval", "contract", "compliance"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "cyber",
    title: "Privileged Access and Configuration Review",
    description:
      "10 controls over the identity-provider export and configuration baseline. Three access exceptions; one review still pending.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "in_review",
    findingId: "F-CYB-001",
    actor: "system",
    searchTags: ["privileged access", "mfa", "access review"],
    coolBacked: false,
  },
  {
    type: "audit",
    scenario: "procurement",
    title: "Vendor Onboarding and Three-Way Match Review",
    description:
      "9 controls over the vendor master, purchase orders, goods receipts, and invoices. Two exceptions; the three-way-match finding was rejected on review.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "exception",
    findingId: "F-PRC-001",
    actor: "system",
    searchTags: ["vendor approval", "three-way match", "PO-9003"],
    coolBacked: false,
  },

  // ── control_test × 11 ────────────────────────────────────────────────────
  {
    type: "control_test",
    scenario: "financial",
    title: "Control REV-REC-01: performance obligation before recognition",
    description:
      "Re-opened the working paper for REV-REC-01. The C-1001/M2 recognition of $1,420,000 still has no delivery date.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "exception",
    findingId: "F-FIN-001",
    actor: "ai",
    searchTags: ["REV-REC-01", "performance obligation", "C-1001", "1420000"],
    coolBacked: true,
  },
  {
    type: "control_test",
    scenario: "financial",
    title: "Control ACC-04: segregation of duties on journal entries",
    description: "Sampled 40 August journals. One entry was posted and approved by the same clerk.",
    auditId: "AUD-FIN-2026-08",
    executionId: "EXEC-FIN-2026-08-001",
    status: "exception",
    findingId: "F-FIN-008",
    actor: "ai",
    searchTags: ["segregation of duties", "journal entry", "accrual"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "financial",
    title: "Control CUT-02: October shipping cut-off sample",
    description: "Matched 31 late-month invoices to bills of lading. Two invoices recognised a day early.",
    auditId: "AUD-FIN-2026-10",
    executionId: "EXEC-FIN-2026-10-001",
    status: "exception",
    findingId: "F-FIN-010",
    actor: "ai",
    searchTags: ["cut-off", "invoice", "october"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "financial",
    title: "Control DEF-11: deferred revenue rollforward",
    description: "Tied the Q4 deferred-revenue rollforward to the contract subledger. One line unexplained.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "exception",
    findingId: "F-FIN-011",
    actor: "ai",
    searchTags: ["deferred revenue", "rollforward"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "legal",
    title: "Control REG-MAP-01: requirement-to-clause mapping",
    description: "GDPR Art.32 security-measures requirement remains unmapped in MSA-7741.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "exception",
    findingId: "F-LEG-001",
    actor: "ai",
    searchTags: ["REG-MAP-01", "gdpr", "MSA-7741"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "legal",
    title: "Control RET-PER-04: record retention period",
    description: "Configured retention is 48 months against a 72-month regulatory minimum.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "exception",
    findingId: "F-LEG-002",
    actor: "ai",
    searchTags: ["retention period", "gdpr"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "cyber",
    title: "Control ACC-MFA-01: privileged multi-factor authentication",
    description: "l.moreau holds a privileged role with MFA disabled.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "exception",
    findingId: "F-CYB-001",
    actor: "ai",
    searchTags: ["ACC-MFA-01", "mfa", "privileged access"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "cyber",
    title: "Control ACC-TERM-02: terminated-user revocation",
    description: "r.dlamini was terminated 2026-08-29; the account is still active.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "exception",
    findingId: "F-CYB-002",
    actor: "ai",
    searchTags: ["terminated access", "ACC-TERM-02"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "procurement",
    title: "Control VEN-APPR-01: vendor master approval",
    description: "PO-9003 was raised against V-503 Pinehurst Consulting with no approval date.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "exception",
    findingId: "F-PRC-001",
    actor: "ai",
    searchTags: ["VEN-APPR-01", "unapproved vendor", "PO-9003"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "procurement",
    title: "Control PO-MATCH-02: three-way match of order, receipt, and invoice",
    description: "VINV-4003 bills 109,400 against a 91,000 purchase order and a 91,000 goods receipt.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "exception",
    findingId: "F-PRC-002",
    actor: "ai",
    searchTags: ["three-way match", "PO-MATCH-02", "invoice"],
    coolBacked: false,
  },
  {
    type: "control_test",
    scenario: "financial",
    title: "Control SOX-404: quarterly walkthrough of revenue close",
    description: "Walked the Q4 revenue-close checklist with process owners. No new exceptions in the walkthrough itself.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["SOX 404", "revenue", "walkthrough"],
    coolBacked: false,
  },

  // ── evidence_review × 7 ──────────────────────────────────────────────────
  {
    type: "evidence_review",
    scenario: "financial",
    title: "Reviewed C-1001 milestone evidence for regional rollout",
    description:
      "Re-read contract C-1001 milestone M2. Due 2026-11-15, delivered: not recorded. This is the evidence behind the September revenue recognition exception.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "completed",
    findingId: "F-FIN-001",
    actor: "ai",
    searchTags: ["C-1001", "contract", "performance obligation", "revenue recognition exception"],
    coolBacked: true,
  },
  {
    type: "evidence_review",
    scenario: "procurement",
    title: "Reviewed 38 purchase orders for October",
    description: "Sampled October POs against the approved vendor list and the authority matrix.",
    auditId: "AUD-PRC-2026-10",
    executionId: "EXEC-PRC-2026-10-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["purchase order", "october", "vendor"],
    coolBacked: false,
  },
  {
    type: "evidence_review",
    scenario: "legal",
    title: "Re-read MSA-7741 security-measures clauses",
    description: "Confirmed the processor agreement still has no Art.32 technical-measures clause.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "completed",
    findingId: "F-LEG-001",
    actor: "ai",
    searchTags: ["MSA-7741", "gdpr", "clause mapping"],
    coolBacked: false,
  },
  {
    type: "evidence_review",
    scenario: "cyber",
    title: "Sampled identity-provider export for privileged users",
    description: "15 privileged accounts reviewed against the MFA and recertification baseline.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "completed",
    findingId: "F-CYB-001",
    actor: "ai",
    searchTags: ["privileged access", "identity provider"],
    coolBacked: false,
  },
  {
    type: "evidence_review",
    scenario: "procurement",
    title: "Inspected vendor master for unapproved suppliers",
    description: "V-503 remains on the master file without an approval date; onboarding in progress.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "completed",
    findingId: "F-PRC-001",
    actor: "ai",
    searchTags: ["vendor master", "unapproved vendor"],
    coolBacked: false,
  },
  {
    type: "evidence_review",
    scenario: "financial",
    title: "Reviewed October bank rec for revenue cut-off",
    description: "Traced the last three business days of cash to invoice dates.",
    auditId: "AUD-FIN-2026-10",
    executionId: "EXEC-FIN-2026-10-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["bank rec", "cut-off", "october"],
    coolBacked: false,
  },
  {
    type: "evidence_review",
    scenario: "procurement",
    title: "Examined change order CO-88 against invoice VINV-4003",
    description: "The reviewer cited CO-88 when rejecting the three-way-match finding. The change order is now on file.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "completed",
    findingId: "F-PRC-002",
    actor: "human",
    searchTags: ["change order", "invoice", "three-way match"],
    coolBacked: false,
  },

  // ── finding × 6 ──────────────────────────────────────────────────────────
  {
    type: "finding",
    scenario: "financial",
    title: "Finding: revenue recognition exception on C-1001 / M2",
    description:
      "F-FIN-001 — high — $1,420,000 recognised against an undelivered performance obligation. Control REV-REC-01. This is the decision the later reconstruction has to explain.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "exception",
    findingId: "F-FIN-001",
    actor: "ai",
    searchTags: HERO_SEARCH_TAGS,
    coolBacked: true,
    pinnedAt: "2026-09-15T11:47:00.000Z",
  },
  {
    type: "finding",
    scenario: "financial",
    title: "Finding: unapproved journal entry above threshold",
    description: "An August accrual of $86,000 was posted without a second approver.",
    auditId: "AUD-FIN-2026-08",
    executionId: "EXEC-FIN-2026-08-001",
    status: "exception",
    findingId: "F-FIN-008",
    actor: "ai",
    searchTags: ["journal entry", "approval", "accrual"],
    coolBacked: false,
  },
  {
    type: "finding",
    scenario: "legal",
    title: "Finding: mandatory GDPR clause unmapped in MSA-7741",
    description: "REG-MAP-01 failed. Art.32 security measures have no corresponding clause.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "exception",
    findingId: "F-LEG-001",
    actor: "ai",
    searchTags: ["gdpr", "REG-MAP-01", "compliance exception"],
    coolBacked: false,
  },
  {
    type: "finding",
    scenario: "cyber",
    title: "Finding: privileged account without multi-factor authentication",
    description: "ACC-MFA-01 failed for l.moreau. Accepted by N. Farrell the same week.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "exception",
    findingId: "F-CYB-001",
    actor: "ai",
    searchTags: ["mfa", "privileged access", "ACC-MFA-01"],
    coolBacked: false,
  },
  {
    type: "finding",
    scenario: "procurement",
    title: "Finding: purchase order raised against an unapproved vendor",
    description: "VEN-APPR-01 — PO-9003 / V-503. Accepted; emergency exception never ratified.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "exception",
    findingId: "F-PRC-001",
    actor: "ai",
    searchTags: ["unapproved vendor", "VEN-APPR-01", "PO-9003"],
    coolBacked: false,
  },
  {
    type: "finding",
    scenario: "financial",
    title: "Finding: deferred revenue schedule incomplete",
    description: "One Q4 deferred-revenue line has no open performance obligation to support the balance.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "exception",
    findingId: "F-FIN-011",
    actor: "ai",
    searchTags: ["deferred revenue", "schedule", "Q4"],
    coolBacked: false,
  },

  // ── follow_up × 6 ────────────────────────────────────────────────────────
  {
    type: "follow_up",
    scenario: "financial",
    title: "Follow-up on F-FIN-001 reversal proposed to the CFO",
    description:
      "CFO pack assembled for the Q3 close. The original September finding is unchanged; this is later correspondence about the reversal.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "in_review",
    findingId: "F-FIN-001",
    actor: "human",
    searchTags: ["F-FIN-001", "reversal", "revenue recognition"],
    coolBacked: false,
  },
  {
    type: "follow_up",
    scenario: "cyber",
    title: "Follow-up on F-CYB-002 remediation",
    description: "Terminated-user account disabled; 31 days of activity pulled for review.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "completed",
    findingId: "F-CYB-002",
    actor: "human",
    searchTags: ["F-CYB-002", "terminated access", "remediation"],
    coolBacked: false,
  },
  {
    type: "follow_up",
    scenario: "legal",
    title: "Follow-up: Art.32 clause amendment drafted",
    description: "Legal operations circulated an MSA-7741 amendment covering technical and organisational measures.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "in_review",
    findingId: "F-LEG-001",
    actor: "human",
    searchTags: ["amendment", "gdpr", "MSA-7741"],
    coolBacked: false,
  },
  {
    type: "follow_up",
    scenario: "procurement",
    title: "Follow-up: V-503 emergency exception ratification",
    description: "Onboarding packet opened for Pinehurst Consulting. The original finding stands.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "in_review",
    findingId: "F-PRC-001",
    actor: "human",
    searchTags: ["V-503", "onboarding", "vendor"],
    coolBacked: false,
  },
  {
    type: "follow_up",
    scenario: "financial",
    title: "Follow-up: October cut-off exceptions cleared",
    description: "Both early-recognition invoices were reversed into November. Working papers updated.",
    auditId: "AUD-FIN-2026-10",
    executionId: "EXEC-FIN-2026-10-001",
    status: "completed",
    findingId: "F-FIN-010",
    actor: "human",
    searchTags: ["cut-off", "reversal", "october"],
    coolBacked: false,
  },
  {
    type: "follow_up",
    scenario: "financial",
    title: "Follow-up: Q4 deferred revenue rollforward tie-out",
    description: "Unexplained line isolated to a prepaid services bundle; schedule restated.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "completed",
    findingId: "F-FIN-011",
    actor: "human",
    searchTags: ["deferred revenue", "tie-out", "Q4"],
    coolBacked: false,
  },

  // ── human_review × 6 ─────────────────────────────────────────────────────
  {
    type: "human_review",
    scenario: "financial",
    title: "J. Okafor accepted the revenue recognition exception",
    description:
      "Senior Manager, Assurance. Decision accepted. Milestone M2 has no delivery evidence and the amount is material. Reversal proposed to the CFO for the Q3 close.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "completed",
    findingId: "F-FIN-001",
    actor: "human",
    searchTags: [...HERO_SEARCH_TAGS, "J. Okafor", "accepted"],
    coolBacked: true,
    pinnedAt: "2026-09-15T14:05:00.000Z",
  },
  {
    type: "human_review",
    scenario: "legal",
    title: "D. Haruna accepted the unmapped GDPR clause finding",
    description: "Head of Legal Operations accepted REG-MAP-01. Amendment drafted.",
    auditId: legalScenario.auditId,
    executionId: legalScenario.executionId,
    status: "completed",
    findingId: "F-LEG-001",
    actor: "human",
    searchTags: ["D. Haruna", "REG-MAP-01", "accepted"],
    coolBacked: false,
  },
  {
    type: "human_review",
    scenario: "cyber",
    title: "N. Farrell accepted the missing-MFA finding",
    description: "Head of Information Security. MFA enforced the same day; privileged role re-attested.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "completed",
    findingId: "F-CYB-001",
    actor: "human",
    searchTags: ["N. Farrell", "ACC-MFA-01", "accepted"],
    coolBacked: false,
  },
  {
    type: "human_review",
    scenario: "procurement",
    title: "S. Varga rejected the three-way-match finding",
    description:
      "Procurement Compliance Lead rejected PO-MATCH-02. Change order CO-88 dated 2026-09-05 sits outside the original evidence set.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "completed",
    findingId: "F-PRC-002",
    actor: "human",
    searchTags: ["S. Varga", "PO-MATCH-02", "rejected"],
    coolBacked: false,
  },
  {
    type: "human_review",
    scenario: "financial",
    title: "M. Reyes verified inventory count variance",
    description: "Plant controller signed the August cycle-count variance memo attached to the accrual review.",
    auditId: "AUD-FIN-2026-08",
    executionId: "EXEC-FIN-2026-08-001",
    status: "completed",
    findingId: "F-FIN-008",
    actor: "human",
    searchTags: ["M. Reyes", "inventory", "variance"],
    coolBacked: false,
  },
  {
    type: "human_review",
    scenario: "financial",
    title: "A. Chen approved the contract modification memo",
    description: "Revenue controller signed the Q4 modification memo for the two clean contracts; the unsigned third remains open.",
    auditId: "AUD-FIN-2026-12",
    executionId: "EXEC-FIN-2026-12-001",
    status: "completed",
    findingId: "F-FIN-012",
    actor: "human",
    searchTags: ["A. Chen", "contract", "modification"],
    coolBacked: false,
  },

  // ── compliance_check × 4 ─────────────────────────────────────────────────
  {
    type: "compliance_check",
    scenario: "financial",
    title: "SOX 404 quarterly control walkthrough",
    description: "Process-owner interviews for the Q4 revenue and close cycle. No design gaps added to the log.",
    auditId: "AUD-FIN-2026-11",
    executionId: "EXEC-FIN-2026-11-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["SOX 404", "compliance", "walkthrough"],
    coolBacked: false,
  },
  {
    type: "compliance_check",
    scenario: "legal",
    title: "GDPR Art.30 records-of-processing attestation",
    description: "RoPA extract attested by legal operations. Two processing purposes pending owner sign-off.",
    auditId: "AUD-LEG-2026-11",
    executionId: "EXEC-LEG-2026-11-001",
    status: "in_review",
    findingId: null,
    actor: "ai",
    searchTags: ["gdpr", "ropa", "compliance"],
    coolBacked: false,
  },
  {
    type: "compliance_check",
    scenario: "cyber",
    title: "ISO 27001 control A.5.15 access-control check",
    description: "Sampled joiner-mover-leaver tickets against the access standard.",
    auditId: "AUD-CYB-2026-10",
    executionId: "EXEC-CYB-2026-10-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["iso 27001", "access control", "compliance"],
    coolBacked: false,
  },
  {
    type: "compliance_check",
    scenario: "procurement",
    title: "Procurement policy POL-PRC-4 annual attestation",
    description: "Category leads attested the current purchasing policy. One region late.",
    auditId: "AUD-PRC-2026-11",
    executionId: "EXEC-PRC-2026-11-001",
    status: "in_review",
    findingId: null,
    actor: "human",
    searchTags: ["policy", "attestation", "procurement"],
    coolBacked: false,
  },

  // ── vendor_review × 4 ────────────────────────────────────────────────────
  {
    type: "vendor_review",
    scenario: "procurement",
    title: "Vendor risk review: Northgate Logistics",
    description: "Annual risk questionnaire and insurance certificates. Residual risk rated medium — concentration on one lane.",
    auditId: "AUD-PRC-2026-10",
    executionId: "EXEC-PRC-2026-10-001",
    status: "completed",
    findingId: "F-PRC-010",
    actor: "ai",
    searchTags: ["northgate", "vendor risk", "logistics"],
    coolBacked: false,
  },
  {
    type: "vendor_review",
    scenario: "procurement",
    title: "Vendor risk review: Pinehurst Consulting",
    description: "Emergency-engaged consultant now going through standard onboarding.",
    auditId: procurementScenario.auditId,
    executionId: procurementScenario.executionId,
    status: "in_review",
    findingId: "F-PRC-001",
    actor: "ai",
    searchTags: ["pinehurst", "vendor risk", "onboarding"],
    coolBacked: false,
  },
  {
    type: "vendor_review",
    scenario: "financial",
    title: "Sanctions screening refresh: Meridian Health Group",
    description: "Customer C-1002 re-screened against the current sanctions list. Clear.",
    auditId: HERO_AUDIT_ID,
    executionId: HERO_EXECUTION_ID,
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["meridian", "sanctions", "C-1002"],
    coolBacked: false,
  },
  {
    type: "vendor_review",
    scenario: "procurement",
    title: "Year-end vendor statement confirmations",
    description: "Sent 40 balance confirmations. 31 returned; 9 being chased for the year-end pack.",
    auditId: "AUD-PRC-2026-11",
    executionId: "EXEC-PRC-2026-11-001",
    status: "in_review",
    findingId: null,
    actor: "ai",
    searchTags: ["vendor statement", "year-end", "confirmation"],
    coolBacked: false,
  },

  // ── access_review × 3 ────────────────────────────────────────────────────
  {
    type: "access_review",
    scenario: "cyber",
    title: "Quarterly administrator access recertification",
    description: "Managers recertified 42 administrator roles. One role outstanding — tracked on AUD-CYB-2026-10.",
    auditId: "AUD-CYB-2026-10",
    executionId: "EXEC-CYB-2026-10-001",
    status: "in_review",
    findingId: null,
    actor: "human",
    searchTags: ["administrator access", "recertification", "access review"],
    coolBacked: false,
  },
  {
    type: "access_review",
    scenario: "cyber",
    title: "Terminated-user access sweep — September leavers",
    description: "11 September leavers. One account (r.dlamini) was the known exception from the September cyber audit.",
    auditId: cyberScenario.auditId,
    executionId: cyberScenario.executionId,
    status: "exception",
    findingId: "F-CYB-002",
    actor: "ai",
    searchTags: ["terminated access", "leavers", "access review"],
    coolBacked: false,
  },
  {
    type: "access_review",
    scenario: "cyber",
    title: "Contractor token expiry review",
    description: "14 contractor tokens due in Q4. Two extended; twelve rotated on schedule.",
    auditId: "AUD-CYB-2026-11",
    executionId: "EXEC-CYB-2026-11-001",
    status: "completed",
    findingId: null,
    actor: "ai",
    searchTags: ["contractor", "token", "access review"],
    coolBacked: false,
  },
];
